version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: vibecoding-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vectordb
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  api:
    build:
      context: ./fastapi
    container_name: vibecoding-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./nginx
    container_name: vibecoding-frontend
    ports:
      - "8080:80" # Use 8080 on host to avoid conflict with other services on 80
    depends_on:
      - api
    restart: always
